version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: proxaudit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - --yes

docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - "sign"
      - "${artifact}@${digest}"
      - --yes

brews:
- name: proxaudit
  repository:
    owner: juliendoutre
    name: proxaudit
    branch: "homebrew-update-{{ .Version	}}"
    pull_request:
      enabled: true
      base:
        owner: juliendoutre
        name: proxaudit
        branch: main
  directory: Formula
  url_template: "https://github.com/juliendoutre/proxaudit/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  dependencies:
    - name: mkcert
      version: 1.4.4

dockers:
  - image_templates:
      - "ghcr.io/juliendoutre/proxaudit:{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/juliendoutre/proxaudit:{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/juliendoutre/proxaudit:{{ .Tag }}"
    image_templates:
      - "ghcr.io/juliendoutre/proxaudit:{{ .Tag }}-amd64"
      - "ghcr.io/juliendoutre/proxaudit:{{ .Tag }}-arm64"
