# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proxaudit < Formula
  desc ""
  homepage ""
  version "0.1.7"

  depends_on "mkcert" => "1.4.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juliendoutre/proxaudit/releases/download/v0.1.7/proxaudit_Darwin_x86_64.tar.gz"
      sha256 "b554bef0f64a30ee6703a47be8408ab83489119d03e37281034716973dd195b1"

      def install
        bin.install "proxaudit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juliendoutre/proxaudit/releases/download/v0.1.7/proxaudit_Darwin_arm64.tar.gz"
      sha256 "1bcaaf92f80ae8975c2f941199810d21ba4051cddc0cd9e29e9b646fd9bbad31"

      def install
        bin.install "proxaudit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/proxaudit/releases/download/v0.1.7/proxaudit_Linux_x86_64.tar.gz"
        sha256 "d4d857044234420e06cba7ad3ab26cc3dcf090e9ae5545671c99f26a96f780e9"

        def install
          bin.install "proxaudit"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/proxaudit/releases/download/v0.1.7/proxaudit_Linux_arm64.tar.gz"
        sha256 "f25f5d1f13ed33a0921ba450ff8c1a3fbd8c878dedbf2b359b876c869073b0cf"

        def install
          bin.install "proxaudit"
        end
      end
    end
  end
end
